# Generated by Django 4.2 on 2023-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("reminder", models.BooleanField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "PAID"), ("unpaid", "UNPAID")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("steam_name", models.TextField(verbose_name="Stream Name")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Goal Amount",
                    ),
                ),
                (
                    "package_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Package Amount",
                    ),
                ),
                (
                    "is_package",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Is Package"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SSLCommerzPaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(blank=True, max_length=200, null=True)),
                ("store_pass", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "is_sandbox",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Please Select No",
                        null=True,
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(blank=True, null=True, verbose_name="Redirect URL"),
                ),
            ],
            options={
                "verbose_name": "SSLCommerz Settings",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sslcommerz", "SSLcommerz")],
                        default="sslcommerz",
                        max_length=20,
                    ),
                ),
                (
                    "tran_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "store_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Store Amount",
                    ),
                ),
                (
                    "tran_status",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("cancel", "Cancel"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="init",
                        max_length=20,
                        verbose_name="Transaction Status",
                    ),
                ),
                (
                    "tran_type",
                    models.CharField(
                        choices=[("payment", "PAYMENT"), ("refund", "REFUND")],
                        default="payment",
                        max_length=10,
                        verbose_name="Transacton Type",
                    ),
                ),
                (
                    "api_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="API Response"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
